version: '3.8'

services:
  frontend:
    build: ./frontend-code
    container_name: demo-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend-code:/app
      - /app/node_modules

  backend:
    build: ./flask-api
    container_name: demo-backend
    ports:
      - "5000:5000"
    volumes:
      - ./flask-api:/app

  cloud-function:
    build: ./gcp-functions
    container_name: demo-function
    ports:
      - "8080:8080"

  nginx:
    image: nginx:alpine
    container_name: demo-nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./infra/nginx.conf:/etc/nginx/nginx.conf
